language: node_js
node_js:
- '5'
before_script:
- npm install -g gulp
script: gulp --release
deploy:
  provider: npm
  email: maxim.novoseltsev.public@gmail.com
  api_key:
    secure: S3ggD9uDpJyPuQDfTEELhc5qI3TqXiDqzibjf2j+YdpVVNJnOnUJsTSQwyopkES5wPvlHTScpGipjYXN1PIfQf5VRmUw1g+1cWst31vRG0+CO4WYIPEiYwCGqcsemUndW8xfLodEhS3maI+OtPD8pIyQmnxw9jjYqOwZdJz5V14R3X/AUrxxL9VPU6pjqY/XFJwZW4b03sbSjlfr7gSazreCIyYU8Kj6fpnovLgDv4Nhrqj/ZBOkDCm/dcaaqqqXJRXINYswlgsER4DE2KzG6rnqb1LOMbSW+0wVpp6cm3V28vHBaWKZFocytfPDyEI031da2zldU8Mtad/JYaeIxjgxUL8CJLUlSAP0g3Yq6riWWgytNpQ1JoNzKOJtSjQNirZOF/mBNHJJd7Z/+y8ebl5iLOS1HJibtjd8igEDrp3TwK8hHgcREGLac/c/D2WqaDXu8pLVZTqoYY51XlsB+oqYhGohMZIWrTEqBIY8yqJVVuEQ0j6NKaD5X8Gltf3kIfORy2sp/tNYRQz61uM/uNB3YR+gEpNNmjzPAkj/TsKEZkpHjQ1ZNe0ZHqSGelOjPz0UqgVYBPy32EoNZWzJ3bD3aOOQy8s/9OgWx5cez/9vEsfjfRg83EV/wkos8JGAL0k/QW9NU77ik+oMA/usXpMUXUMkonZuqA72XdXf+7s=
  on:
    tags: true
    repo: tov-Novoseltsev/state-proxy
